imports:
    - { resource: ../config.yml }
    - { resource: ../config_env.yml, ignore_errors: true }

services:

    db_conn:
        factory_class: Doctrine\DBAL\DriverManager
        factory_method: getConnection
        arguments: ['%database%']
